### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by Greaby** [Greaby/telescope#1]

**Comment by agentcobra** [comment]
Hi,
how to install it?

**Comment by Greaby** [comment]
Hello,
I added some documentation to the readme. 
Feel free to tell me if some things are not clear.

**Comment by agentcobra** [comment]
Thanks for bbed5a4879ac8ca7383ec4cc6dbcbc4484dec8b2 
I was trying with ```npm run start```

**Comment by belgianGeek** [comment]
Hi !

Wouldn't it be better to add some template files (like a Telescope introduction or whatever) in the `data/resources` folder to make the project setup easier than saying in the README _Look, you need to add some files in this folder and following this template to make things work_ ?

I think it would be easier for everyone if we could just include some templates they can start with, which they can modify to suit their needs. I can submit a PR following your decision @Greaby. :wink:

What do you think ?

**Comment by Greaby** [comment]
Yes, that's a great idea.
My plan was to create the documentation and examples directly using Telescope and host it on Github pages.

**Comment by belgianGeek** [comment]
Indeed, why not ? It would be a great way to show exactly how the software works !
Do not hesitate to ask if you need some help to set the thing up. :wink:

**Comment by Greaby** [comment]
I'm not the best for documentation ;)
So yes, I do appreciate the help

**Comment by belgianGeek** [comment]
Nice ! I'll try to submit a PR when I'll have had enough time to really understand how Telescope works. :smiley: Should I post my suggestions here or do you prefer another platform (Discord, Github Discussions, email...) ?

**Comment by Greaby** [comment]
You can post your suggestions wherever you like. But I think it's best to make issues here.

**Comment by Greaby** [comment]
I have created a sample structure for the documentation:
https://greaby.github.io/telescope/

I used Telescope 0.8.0 which is not yet committed on Github.  The project uses the new metadata system as described here: #14

**Comment by belgianGeek** [comment]
Hi ! I just had a look and it is really impressive ! Well done !

I didn't have enough time yet to think about **how** exactly I could write documentation or help you in any other way, but I successfully hosted my own instance on [https://www.maxvdw.ovh/open-planner-docs](https://www.maxvdw.ovh/open-planner-docs). Still a WIP, but it works really well. 😃 

Also, the idea described in #14 is really good. I'm really looking forward to use it !

**Comment by Greaby** [comment]
Documentation is here !
I will close this issue and create a new one to complete the doc.  #15
