### ISSUE TITLE
Rename the /data folder to /docs to make Github Pages hosting possible ?

### ISSUE THREAD

**Issue by belgianGeek** [Greaby/telescope#11]
Hi !

I recently discovered your project thanks to [this article from korben.info](https://korben.info/telescope-graph.html). It wanted to try it out to host the documentation of one of my project. I planned to host it with Github Pages as it is a free and reliable service which I'm already using for my blog.

The thing is, I can't host it through Github Pages because there isn't a `docs` folder. Could renaming the `data` folder be sufficient for this use case ? Do you agree to make such a modification globally or to help me modify it in my own fork ?

As I have an intermediate level in JS, I can help you if you need/want to. 😉

Thanks !

**Comment by belgianGeek** [comment]
Nevermind, I think I misunderstood my problem, which actually isn't linked to your project's structure in any way.

I'm closing the issue. Thank you and please accept my apologies for the hassle. 😶

**Comment by Greaby** [comment]
No worries!
Thanks for using Telescope. :)
