### ISSUE TITLE
Unable to start Telescope - cannot find module index.js

### ISSUE THREAD

**Issue by belgianGeek** [Greaby/telescope#12]
Hi !
I tried to run Telescope after cloning the repo locally and installing the dependencies through Yarn. When I wanted to start the program, it threw an error saying the `index.js` file is missing. I just cloned the repo and installed all the dependencies, without touching at anything yet. Here's a screenshot of the error :

![Yarn start error screenshot](https://user-images.githubusercontent.com/39968047/149761894-7d33633f-dc15-4a59-afad-58d232c63043.png)

Here's my directory structure :
![directory structure](https://user-images.githubusercontent.com/39968047/149762251-615a9e8f-547d-4c81-8142-364d63ce7b90.png)

Can you help me with this ?
Thanks a lot !

**Comment by agentcobra** [comment]
@belgianGeek see #1

**Comment by Greaby** [comment]
Sorry I left the `start` command which is not used.
Use `yarn build` instead.

I don't use yarn. If there are errors, I can make the project compatible with it.

**Comment by belgianGeek** [comment]
Thank you all ! 😃 

I also tried `npm run build`but I received the following error output :
![image](https://user-images.githubusercontent.com/39968047/149772473-82dd7893-0d28-4cff-833a-54e8dedb5272.png)

I did some research but I do not know how to solve it so far... 🤔 Can you help me out ?
Thanks

**Comment by belgianGeek** [comment]
I actually managed to get it working by adding some Markdown content in the `data/resources` folder, as mentioned in the README. I might submit a PR in the next few days to update the documentation and make it clearer about the setup process.

Thank you for this project, I'm really excited to use it ! :smiley:

**Comment by Greaby** [comment]
Yes, this error occurs when the project is empty.
I created this issue : #13 

Thanks in advance for your PR ! ;)
