### ISSUE TITLE
Manage additional types of metadata

### ISSUE THREAD

**Issue by Philippe-Arnaud** [Greaby/telescope#14]
The current architecture limits the type of metadata that can be generated to Authors and Tags.

In order to possibly expand the schema of data, it could be useful to be able to create additional types of metadata, preferably generated on the fly.
While tags could be used for that, the fact is that some key reference information would end-up being buried in the tags structure.

I'm especially thinking about custom classifications entry points such as Services, Applications or Criticality for technical documentation.

Being able to qualify cards with this kind of custom metadata would be, from my point of view, a huge addition to the navigation in the data managed by Telescope.

**Comment by Greaby** [comment]
Thanks for your suggestion, the idea is really good.

An "On the fly" approach is possible and would provide more flexibility to the project.
I built the project with a focus on an academic documentation approach. I didn't see the other possible uses for it.

In summary, these are the key changes:

- By default, every metadata is used "on the fly" to generate the graph. (Authors and Tags will no longer be hard-coded)
- On the html page of a resource, each metadata is displayed in the same way as the tags currently.
- A random color is choosen according to the name of the metadata.
- Possibility to customize the metadata in the config (Label, color, displayed on the graph, on the html page, searchable)

**Comment by Greaby** [comment]
I think this will also facilitate the creation of the Telescope documentation #1
